import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Manrope } from "next/font/google";
import type { ReactNode } from "react";
import { cn } from "@/modules/shadcn/lib/utils";
import Providers from "@/shared/providers/Providers";
import "./globals.css";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable, manrope.variable)}>
      <body
        className={cn(geistSans.variable, geistMono.variable, 'antialiased flex flex-col bg-launcher h-screen border muted-border')}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
